import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  basePath: '/miserviciotecnico',
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.VITE_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? process.env.VITE_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID ?? process.env.VITE_EMAILJS_SERVICE_ID,
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID ?? process.env.VITE_EMAILJS_TEMPLATE_ID,
    NEXT_PUBLIC_EMAILJS_TEMPLATE_BUSINESS_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_BUSINESS_ID ?? process.env.VITE_EMAILJS_TEMPLATE_BUSINESS_ID,
    NEXT_PUBLIC_EMAILJS_TEMPLATE_CLIENT_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_CLIENT_ID ?? process.env.VITE_EMAILJS_TEMPLATE_CLIENT_ID,
    NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY ?? process.env.VITE_EMAILJS_PUBLIC_KEY,
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ?? process.env.VITE_GOOGLE_MAPS_API_KEY,
    NEXT_PUBLIC_BUSINESS_EMAIL: process.env.NEXT_PUBLIC_BUSINESS_EMAIL ?? process.env.VITE_BUSINESS_EMAIL,
    NEXT_PUBLIC_BUSINESS_PHONE: process.env.NEXT_PUBLIC_BUSINESS_PHONE ?? process.env.VITE_BUSINESS_PHONE,
    NEXT_PUBLIC_BUSINESS_ADDRESS: process.env.NEXT_PUBLIC_BUSINESS_ADDRESS ?? process.env.VITE_BUSINESS_ADDRESS,
    NEXT_PUBLIC_BUSINESS_HOURS: process.env.NEXT_PUBLIC_BUSINESS_HOURS ?? process.env.VITE_BUSINESS_HOURS,
    NEXT_PUBLIC_BUSINESS_COORDINATES_LAT: process.env.NEXT_PUBLIC_BUSINESS_COORDINATES_LAT ?? process.env.VITE_BUSINESS_COORDINATES_LAT,
    NEXT_PUBLIC_BUSINESS_COORDINATES_LNG: process.env.NEXT_PUBLIC_BUSINESS_COORDINATES_LNG ?? process.env.VITE_BUSINESS_COORDINATES_LNG,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'lysejfhxackcmoksclvm.supabase.co',
      },
    ],
    unoptimized: true,
  },
};

export default nextConfig;
